### ISSUE TITLE
Legistar zero events bug

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/civic-scraper#158]
As part of the [Legistar refactor](https://github.com/biglocalnews/civic-scraper/pull/154), noticed that [python-legistar-scraper](https://github.com/opencivicdata/python-legistar-scraper/) is returning zero "events" for the following sites in `tests/legistar_site.py`. Haven't pinpointed the precise nature of the issue, but it appears to be something with the underlying framework (as opposed to the civic-scraper [`legistar.site.Site`](https://github.com/biglocalnews/civic-scraper/blob/master/civic_scraper/platforms/legistar/site.py#L15) implementation). 

Below is a list of the sites where events are not being captured as expected:

- https://petersburg.legistar.com/Calendar.aspx
- https://goodyear.legistar.com/Calendar.aspx
- https://paradisevalleyaz.legistar.com/Calendar.aspx
- https://alameda.legistar.com/Calendar.aspx
- https://actransit.legistar.com/Calendar.aspx
- https://fresnocounty.legistar.com/Calendar.aspx
- https://fullerton.legistar.com/Calendar.aspx

**Comment by zstumgoren** [comment]
@antidipyramid Thanks for pinning down the details! Sounds good on the fix for (1). For (2), it would be great to handle the non-updating sites for the purposes of backfilling, although we'll need to flag and investigate those agencies to determine if they're using some new site to post agendas, minutes, etc. On (2), would the fix need to happen on our end in the civic-scraper framework?

**Comment by antidipyramid** [comment]
@zstumgoren No, if we want to account for non-updated sites like Goodyear, the fix needs to happen in the Legistar scraper.

**Comment by fgregg** [comment]
This has been fixed.
