### ISSUE TITLE
Define and implement command line invocation, if any, for `civicplus.py` and other scrapers

### ISSUE THREAD

**Issue by chris-stock** [biglocalnews/civic-scraper#29]
Right now, there's a command line invocation for `civicplus.py` that's out of date. 

I'm not sure it's necessary that the files `scrapers/*.py` have command line invocations at all -  I'd recommend getting rid of them since we now have other scripts that basically wrap around the individual scrapers.

But if we want to keep command line invocations at the level of individual scrapers, let's decide what they should be, then update them accordingly.

**Comment by zstumgoren** [comment]
Closing in favor of #76
