### ISSUE TITLE
Define and implement command line invocation, if any, for `asset.py`

### ISSUE THREAD

**Issue by chris-stock** [biglocalnews/civic-scraper#34]
Right now the command line invocation of asset.py is hard coded to work for Amy's computer.

It's not clear to me that any command line invocation of this file is necessary at all - I can't think of what I'd want to do with Asset or AssetCollection from the command line (I'm certainly not going to be in the business of constructing an Asset instance by writing out all the asset fields as individual command line arguments, for example).

I suggest scrapping the command line invocation of `asset.py`, or otherwise defining what you want it to do and updating it.

**Comment by zstumgoren** [comment]
Closing in favor of #76
