### ISSUE TITLE
Update civicplus scraper to capture entity metadata

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/civic-scraper#37]
Let's perform a level of effort assessment on how to gather entity metadata (e.g. committee name, type and jurisdiction level such as city vs county). This is a blocker for including an entity-based filter or search feature for our v1 design.

**Comment by DiPierro** [comment]
@zstumgoren Are we satisfied with the metadata we've collected now?

**Comment by zstumgoren** [comment]
@DiPierro I think? But probably worth a wider conversation at our next team meeting before closing this one
