### ISSUE TITLE
File handle error for Windows users 

### ISSUE THREAD

**Issue by krammy19** [biglocalnews/civic-scraper#46]
Hi Stanford team, 

Some members of our team are getting a consistent error with the file names in the testing folder. It seems like Windows users can't clone the repo because of a colon used in the filename: 

Example: 

'testing/civicplus.py_v2020-07-09-no_data-no_data-2020-07-18T15:59:03.943461.csv'

Cloning fails with this error: 

Cloning into 'C:\Users\Krammy\Documents\GitHub\civic-scraper'...
remote: Enumerating objects: 333, done.        
remote: Counting objects: 100% (333/333), done.        
remote: Compressing objects: 100% (238/238), done.        
remote: Total 3295 (delta 204), reused 209 (delta 94), pack-reused 2962        
Receiving objects: 100% (3295/3295), 34.10 MiB | 8.63 MiB/s, done.
Resolving deltas: 100% (622/622), done.
error: invalid path 'testing/civicplus.py_v2020-07-09-no_data-no_data-2020-07-18T15:59:03.943461.csv'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Is there another way to name these files?

**Comment by zstumgoren** [comment]
I just updated file names to remove the colons. Can you test cloning again and let us know how it goes?

**Comment by krammy19** [comment]
It cloned like a charm! Thanks!
