### ISSUE TITLE
Create a master list of platforms scrape

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/civic-scraper#48]
We need a list of platforms to target. We have some of this information in various scattered places such as:

*  [this doc](https://docs.google.com/spreadsheets/d/1Neoyt7e2BnF5Wd5KmTMrOmoyrSK8dTTHSZdFBavjPRI/edit#gid=0)
* #15
* #14
* #16

Let's gather up our scattered resources and create a centralized public list of platforms to target. 

As part of this, let's note for each platform a handful of example sites that correlate to the various versions for a given platform (if there are multiple versions).

**Comment by DiPierro** [comment]
Here's a draft of a master list: https://docs.google.com/spreadsheets/d/1o91bAiLgakIEyIGZS_wfZ6g6Cla5C6eeswi2KFPnEME/edit#gid=0
cc @zstumgoren

**Comment by zstumgoren** [comment]
@DiPierro List looks great! Thanks Amy!
