### ISSUE TITLE
test_download_asset_list fails

### ISSUE THREAD

**Issue by DiPierro** [biglocalnews/civic-scraper#63]
In `test_asset.py`, this function fails. We need to:
- [ ] diagnose the problem
- [ ] fix the problem

**Comment by DiPierro** [comment]
Update: #61, #62, #63 and the content-type errors in #58 are all caused by the fact that these websites have added a Captcha feature, which to my knowledge is new as of this winter. See image below for an example. 
![image (2)](https://user-images.githubusercontent.com/25288085/101791946-fabcc200-3ab8-11eb-8e31-a7f979ccaf9c.png)

**Comment by DiPierro** [comment]
Update: This Captcha does not appear to be a problem within the U.S., meaning there must be some other issue for sites like napa-county.civicplus.com. I'm having trouble fixing the bug because I continue to hit this Captcha page when running the scraper from my machine in the UK. I can revisit this bug when back in the states or another contributor can take a look in the mean time.

**Comment by zstumgoren** [comment]
@DiPierro Agreed, this is not a captcha issue. However, the `napa-county.civicplus.com` subdomain is not currently responsive. Instead, the AgendaCenter site appears to be live at a non-CivicPlus domain:

```
https://www.countyofnapa.org/AgendaCenter
```

It appears we'll need to be prepared to handle AgendaCenter sites that are not subdomains of `civicplus.com`. I've re-opened an issue (#80) to address this issue on the `refactor` branch and a research ticket (#82) to determine the extent of the issue.
